# Generated by Django 4.2.6 on 2023-11-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='produtos/')),
            ],
        ),
    ]
