# Generated by Django 4.2.6 on 2023-11-23 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_loja', '0003_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(choices=[('batizado', 'Batizado'), ('debutante', 'Debutante'), ('casamento', 'Casamento'), ('aniversario', 'Aniversário')], max_length=20)),
                ('massa', models.CharField(choices=[('baunilha', 'Baunilha'), ('cenoura', 'Cenoura'), ('paodelo', 'Pão de Ló'), ('festa', 'Festa')], max_length=20)),
                ('recheio', models.CharField(choices=[('brigadeiro', 'Brigadeiro'), ('docedeleite', 'Doce de Leite'), ('abacaxi', 'Abacaxi'), ('morango', 'Morango')], max_length=20)),
                ('data_entrega', models.DateField()),
                ('detalhes', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
